/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LiveRouteImport } from './routes/live'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as PlayCallingRouteImport } from './routes/play-calling'
import { Route as QbRouteImport } from './routes/qb'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCallingRoute = PlayCallingRouteImport.update({
  id: '/play-calling',
  path: '/play-calling',
  getParentRoute: () => rootRouteImport,
} as any)
const QbRoute = QbRouteImport.update({
  id: '/qb',
  path: '/qb',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/live': typeof LiveRoute
  '/optimizer': typeof OptimizerRoute
  '/play-calling': typeof PlayCallingRoute
  '/qb': typeof QbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/live': typeof LiveRoute
  '/optimizer': typeof OptimizerRoute
  '/play-calling': typeof PlayCallingRoute
  '/qb': typeof QbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/live': typeof LiveRoute
  '/optimizer': typeof OptimizerRoute
  '/play-calling': typeof PlayCallingRoute
  '/qb': typeof QbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guide' | '/live' | '/optimizer' | '/play-calling' | '/qb'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guide' | '/live' | '/optimizer' | '/play-calling' | '/qb'
  id:
    | '__root__'
    | '/'
    | '/guide'
    | '/live'
    | '/optimizer'
    | '/play-calling'
    | '/qb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRoute
  LiveRoute: typeof LiveRoute
  OptimizerRoute: typeof OptimizerRoute
  PlayCallingRoute: typeof PlayCallingRoute
  QbRoute: typeof QbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-calling': {
      id: '/play-calling'
      path: '/play-calling'
      fullPath: '/play-calling'
      preLoaderRoute: typeof PlayCallingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qb': {
      id: '/qb'
      path: '/qb'
      fullPath: '/qb'
      preLoaderRoute: typeof QbRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRoute,
  LiveRoute: LiveRoute,
  OptimizerRoute: OptimizerRoute,
  PlayCallingRoute: PlayCallingRoute,
  QbRoute: QbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
